<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <!-- 
	  <TargetFramework>{TargetFramework}</TargetFramework>
	 -->
	  <TargetFramework>net8.0</TargetFramework>

	  <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.30" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HybridOnionCleanApiTemplate.Domain\HybridOnionCleanApiTemplate.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Core">
      <HintPath>..\..\..\DLLs\Core.dll</HintPath>
    </Reference>
    <Reference Include="GenericRepository">
      <HintPath>..\..\..\DLLs\GenericRepository.dll</HintPath>
    </Reference>
    <Reference Include="Resources">
      <HintPath>..\..\..\DLLs\Resources.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
