<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <PackageId>HybridOnionCleanTemplate</PackageId>
    <PackageVersion>1.0.1</PackageVersion>
    <PackageTags>dotnet-new;templates</PackageTags>
    <Authors>Freddy Soto</Authors>
	<Company>{CompanyKey}</Company>
	 <!-- 
	 <TargetFramework>{TargetFramework}</TargetFramework>
	 -->
	  <TargetFramework>net8.0</TargetFramework>
	  <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="8.0.30" />
    <PackageReference Include="System.Security.Claims" Version="4.3.0" />
	  <!-- Brand-specific packages -->
	  <!--#if (Company == "Company")-->
	  <!--#endif-->
	  <!--#if (Company == "Company")-->
	  <!--#endif-->
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\HybridOnionCleanTemplate.Application\HybridOnionCleanTemplate.Application.csproj" />
    <ProjectReference Include="..\HybridOnionCleanTemplate.Infrastructure\HybridOnionCleanTemplate.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Components">
      <HintPath>..\..\..\DLLs\Components.dll</HintPath>
    </Reference>
    <Reference Include="Core">
      <HintPath>..\..\..\DLLs\Core.dll</HintPath>
    </Reference>
    <Reference Include="Logger">
      <HintPath>..\..\..\DLLs\Logger.dll</HintPath>
    </Reference>
    <Reference Include="Middlewares">
      <HintPath>..\..\..\DLLs\Middlewares.dll</HintPath>
    </Reference>
    <Reference Include="Models">
      <HintPath>..\..\..\DLLs\Models.dll</HintPath>
    </Reference>
    <Reference Include="Notifications">
      <HintPath>..\..\..\DLLs\Notifications.dll</HintPath>
    </Reference>
    <Reference Include="Resources">
      <HintPath>..\..\..\DLLs\Resources.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
