<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <!-- 
	  <TargetFramework>{TargetFramework}</TargetFramework>
	 -->
	  <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.30" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HybridOnionCleanTemplate.Domain\HybridOnionCleanTemplate.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="GenericRepository">
      <HintPath>..\..\..\DLLs\GenericRepository.dll</HintPath>
    </Reference>
    <Reference Include="Resources">
      <HintPath>..\..\..\DLLs\Resources.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
